### ISSUE TITLE
Why can't I use it on some places like Spotlight and Lookup sheet?

### ISSUE THREAD

**Issue by iammvaibhav** [NSExceptional/FLEXing#33]
I'm not able to select result items in the Spotlight using FLEX. It actually taps that item instead of FLEX giving details about it. Am I doing something wrong or is this the expected behavior?

**Comment by NSExceptional** [comment]
Those are in different processes. Spotlight is its own app now. You will need to activate it from spotlight using the 3 finger long press gesture

**Comment by iammvaibhav** [comment]
Thanks for the info. I was able to activate it on the spotlight with the three-finger gesture but still no luck with the lookup sheet. 
Steps to reproduce: select a text -> Click on lookup -> try to use the three-finger gesture here

**Comment by NSExceptional** [comment]
That is also out of process, just like safari view controller. Not sure how to activate it there. It would probably require a lot of re-architecting of FLEX because FLEX uses its own window, and these views are not window, just views. FLEX would need to be able to present itself in a view rather than an app.
